name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependancies
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt -y install tzdata
        sudo apt -y install libgtkmm-3.0-dev libcurl4-openssl-dev libsqlite3-dev
    - name: make
      run: make BUILD=release
    - name: make_deb
      run: ./make_deb_24.sh
