name: Upload files to release

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      id-token: write
      contents: write 
      attestations: write
      actions: read
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependancies
      run: |
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt -y install tzdata
        sudo apt -y install libgtkmm-3.0-dev libcurl4-openssl-dev libsqlite3-dev
    - name: make
      run: make BUILD=release
    - name: make_deb
      run: ./make_deb_24.sh
    #- name: create sbom
    #  uses: anchore/sbom-action@v0
    #  with:
    #    output-file: release/Ubuntu24/is-online_sbom.spdx
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
       subject-path: |
         build/release/is-online
         release/Ubuntu24/is-online_${{github.event.release.tag_name}}_amd64.deb
         release/Ubuntu24/SHASUMS
    #- name: Generate SBOM attestation
    #  uses: actions/attest-sbom@v1
    #  with:
    #    subject-path: build/release/is-online
    #    sbom-path: release/Ubuntu24/is-online_sbom.spdx
    - name: Upload build files to release
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      run: |
        gh release upload ${{github.event.release.tag_name}} release/Ubuntu24/is-online_${{github.event.release.tag_name}}_amd64.deb
        gh release upload ${{github.event.release.tag_name}} release/Ubuntu24/is-online
        gh release upload ${{github.event.release.tag_name}} release/Ubuntu24/SHASUMS